Fix compat with linux > 6.1 headers
In file included from /usr/include/linux/btrfs.h:29,
                 from ../linux-user/syscall.c:163:
/usr/include/linux/fs.h:50:8: error: redefinition of 'struct file_clone_range'
   50 | struct file_clone_range {
      |        ^~~~~~~~~~~~~~~~
../linux-user/syscall.c:129:8: note: originally defined here
  129 | struct file_clone_range {
      |        ^~~~~~~~~~~~~~~~

was caused by btrfs.h gaining an include of linux/fs.h,
which clashed with QEMU's workaround for glibc compat
with linux/mount.h.  GLibc huas fixed their sys/mount.h
so we can drop the QEMU workaround, thus fixing the
btrfs.h problem.

Signed-off-by: Daniel P. Berrangé <berrange@redhat.com>